[[default]]
arch = "aarch64"
git-tree-sha1 = "c9751a3e9be512c80cdcb1ede9949baac9e62ae7"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "2ecca7e4ed0ae557abf5c6571fb99cf58d907360d3ef073d97ff315b44d55d96"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "58efdf030f3a1862a995cba4b9aa306cb5739afe"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "b0bcabcdf76e3364871c5889ddb1ca28ada3fc54823e76e09225d22077a550f7"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "feb9041ffd3441156d9480ffc6e236503544bf75"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "f1d795723e44df8f7f5f5b07a4417d7d9b593cd2ff309d03c5d4d5072d95ee90"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
