[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "4cdb2bbcd37cca173bbbedd7e547c9e6ce418366"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "d3939599d2a705ecce929a51aa2866c938d05ba8faac58928207a924abe45ee0"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "ecc126c939192390905e3d1e897cd1520a2271a3"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "d0dd0011cc554c5cba2bf49ff20f0a3aa0fb1f69f62a33cfd0f15a5fcd62defa"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "dc7bb05045ef7dfcc129e68173212d8e4c3010df"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "156480d9549f9204a957ad1a4dd3afc4b9685f7bab93bd24983944fe4f4b2877"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
