[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "0e4e2f035ff1a99b5854e81b6bb10711c8fc0049"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "65dac3d04325e11f743d07e5da0fe92ba3412615bdcebd7af49ad89d8d9cbe18"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "b21fcfd83e7e0fcbb3c50185c02969ab822f9b38"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "805ad978767d1c0e35b66003a1578fb8fb62bfa2418943975c177bb67ae9cff2"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "29576c2a85a37977db5ca0de0591f4ca12f44cbb"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "86b92b1017294ff70da0591a783c810ae99d21603857048af0f41468b22dcaf3"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
