[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "10d2affaee7da0ead2f0f9934c78172cac09fcfa"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "6e57a4d40815c0fe4fcdb1e6f9bb1f5d2b027283e71727535b08e4d81a1ea3f1"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.15-GCCBoostrap/Ncurses-v1.0.15-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "39bc3bf6e363c97aff6db5074cd5dd639761dd3d"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "150ad6698223da57cf09d3198b75e3caceaae9a1cff396cd8adfbcbe93fea2ee"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.15-GCCBoostrap/Ncurses-build_log-v1.0.15-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "7c658e670e1fe4785d71daf1f443c3f68ccc6c15"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "2972b9831d6535f2ddcb30eb61534588aa2b309842f82a847191db332ac14a82"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.15-GCCBoostrap/Ncurses-extract_log-v1.0.15-x86_64-linux-gnu.tar.gz"
