[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "ba7d02890d2a36339e6736d808a4767634c97a30"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "ba3b5ba99d6cdccf8425f37c9bffb54da28d08487a9fa4f1acc4cc81de70b7ba"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap-x86_64-linux-gnu/Ncurses-v6.4.4-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "5eab829804ab3dfc56f228b3188e2aa505a21644"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "0083d29a0e01de14f5a3a7eaa393e375bd4ff2d398c90945a7d049173c09218b"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap-x86_64-linux-gnu/Ncurses-build_log-v6.4.4-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "757564895024bed42d9d935b3a2e20f75b48d2c8"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "4fcb1c4c3baa9464d72dd3204708d3058d328d0fdaa4ec5a8c13ce14862c43f7"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap-x86_64-linux-gnu/Ncurses-extract_log-v6.4.4-x86_64-linux-gnu.tar.gz"
