[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "96cec9c6e1cb4b7f3eb6d978a4ef4e25061e4fc8"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "1fca8312bc31220b869d905b148190886732ed03b9691c7cbddec42e26df7d1c"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "cd4c17434aca2b338315043207c37d5b35269f66"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "02f7320e2a8362572af8afbb8344fb78ecf0cfd7998883b98300ad6f11be8bf6"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f336af8a8665a07d699ac8f499f633df874cc2fe"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "55907f09228507b90ac1640454498c0913abbebfccab890e2ff09d3756d631c2"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
