[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "07038fe342bf02cd323c56032d878d4fcc74fb48"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "cc5c994d730b750807b8b4103ad9e75b649baf8e9c6c402bf54f59486f06ad42"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBootstrap-x86_64-linux-gnu/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "6d6cc1e222565317518fe697e845c206bca5d109"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "1eff5d4221db765a688a44efff19f1dc586ca8e410c0631308fffd53071b1bd5"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBootstrap-x86_64-linux-gnu/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b6e72d1e47e24c8a8302ed0a26ece3336334a675"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "fdc8ce51129b68ed3b3c6d113cc705354f5cd1d6b9410d006f6a77c872223799"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBootstrap-x86_64-linux-gnu/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
