[[default]]
arch = "aarch64"
git-tree-sha1 = "797b5ebd96473be0bcf2000fb03e03ff85d09d95"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "17dbc27704b0f88aec15f89e7971f48857a2ce3dc5bc6bcfc7abe4b9d82c06bd"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "54e9daf6c992a20ee6697442e16d761e969ed8ba"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "1faf8cffa32d3a27fe9b96b97a56a8c23f46c0a65d70cd7b36bec71c66ba9a7b"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "feb9041ffd3441156d9480ffc6e236503544bf75"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "c286489d89c78e55593e827ac55ce4d6cd74146c1aae32d3d316e537334af008"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
