[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "084c0d1ac481ae981cf08e11eab27b944f1f6ea3"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "f453cebb46b7e56ba4e2e2e852388b47acc5308a79073e3cfb06df88b8a4f55c"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBootstrap-x86_64-linux-gnu/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "fd258836c10e90af3bbb7e492b346bbb9ac034f6"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "3dedc411b17993f33086415c4f5a274b087d3d86cb6adcbb54e0ef7e1259d6c6"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBootstrap-x86_64-linux-gnu/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "317a919ca7084ef3e1134e6269ab015f45853643"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "70644c2e0ab2e0d15449460dbedb38487f7fd07ba4a3e533a689c255b2f128bf"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBootstrap-x86_64-linux-gnu/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
