[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "95003beda71808a2ceaa7b80c142e3381e068336"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "6678a3ffffa86a94f1f51392a97db762bd4f470e3010972732e4d3235c146a10"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "266337f46c54665886b014368eecae5eb964355c"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "091553c45bc5cdce75855116c9604dcd387f2b6671324b12579ca703baa7ee7a"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "127ae73eb3da62c3ca703e36ce3e4ff37a5cdada"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "9f11dc4194407c5e8fa480289f67949296077dad105e0d873c7e2b39f45a73d1"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
