[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "878c086b5c47c2ae924784e33e207fd90d5afb10"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "1f655231638020bbe6a070500c2dc81df79c0b4d28170c299c0db999d44ac374"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "a5c03066d3513fb920a2fa36f378d72e1a0b3b82"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "f7a75f2f22d5b885ba2c2c0d74cb98a52121e81b534da75d4337f6a23eb8b95e"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-v6.4.2-i686-linux-gnu.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "11546f8e24d870c97f4641fb950522445bb95487"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "b5dd8e70803e5385e73d99c8688c988a5f488b1a0effafa42f47815f39200a48"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-v6.4.2-aarch64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7f0bad2b60a975368106a29aa07b1ae89f6577f9"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "61cbfabef6f5c53dd54b57482403024e4501c6ffe61279b35b89a10d8bab97f0"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-v6.4.2-armv7l-linux-gnueabihf.tar.gz"
[[Ncurses]]
arch = "powerpc64le"
git-tree-sha1 = "eb1b898a44c9fb4c5d6ae1eb4d1c90896612cc4e"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "3a4485a8b71b2222a3ea5aac177a696a8580e63adaec81459b42578fcde20eb0"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-v6.4.2-powerpc64le-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "ae6d3df1dd4d47772080a07a47bb760aa93c49ce"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "8b5d3095abebf5e6de02e16247be6817856c66d1be20a293fdb6ba21eb4615cc"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"
[[Ncurses-build_log]]
arch = "i686"
git-tree-sha1 = "06cf85db72e2743408345cf330a3b5bf2aa800a8"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "21650b7780b3ebaaf6c6dbfecf71f290a03ffc96bd3afc0b6d4ae29589641597"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-build_log-v6.4.2-i686-linux-gnu.tar.gz"
[[Ncurses-build_log]]
arch = "aarch64"
git-tree-sha1 = "53a9124d101d1e63fcbd2c0527d7e7994b748b75"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "c085eb12367fd8d434bbf4cefdfd06ebcd9afd39692b2aee2ce59d740b6311e5"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-build_log-v6.4.2-aarch64-linux-gnu.tar.gz"
[[Ncurses-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2b9d5177fb0f26b93613024246a46ed247970d1c"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "11ddca0878e28379aea940bc64bfce42436b25c6276a3ea632e281cb08ca2e8a"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-build_log-v6.4.2-armv7l-linux-gnueabihf.tar.gz"
[[Ncurses-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "6635e06ae6e00ed01a2339cde43f785fc944a753"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "3a318fa8b5ea97111ea6960ae9b79fe2aa24913e67817116c6184cb2667b348c"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-build_log-v6.4.2-powerpc64le-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "78fe11ad41897ae79b66c7ee90c3ec1694c89c77"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "cb10a165f05beef1c60787ffc44b5caf32b70a6cb2fa2198bfeb536c8b8f429e"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
[[Ncurses-extract_log]]
arch = "i686"
git-tree-sha1 = "fcf45fba503da2f7c1b66a8440e0e730c2bb65ad"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "cdb7b386a21fd97f21e012bef16db9349302468702bce3a780ab2a218070ee3a"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-extract_log-v6.4.2-i686-linux-gnu.tar.gz"
[[Ncurses-extract_log]]
arch = "aarch64"
git-tree-sha1 = "43bf5fbf088fd44e4ffa6efcdcfc1335a864b08a"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "e4d4d88c41fe08cd37b809eadae9b933aebfcd8a486d44000163c5262feac6b3"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-extract_log-v6.4.2-aarch64-linux-gnu.tar.gz"
[[Ncurses-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48e882e78ac9ab2f16201741aa87356bdf8a3c47"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "f6e21d8bdcbae0b6e6980cbdd1578dae7c5ea76463f3768d6ebe2998f4dde6ff"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-extract_log-v6.4.2-armv7l-linux-gnueabihf.tar.gz"
[[Ncurses-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "2e4e8c3c716b494fa9541e0638e50e4729f5ec74"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "73e7dd2a1d8392276df13d841d9a0d40aa575a6501148c689beb778e4869e984"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCC/Ncurses-extract_log-v6.4.2-powerpc64le-linux-gnu.tar.gz"
