[[default]]
arch = "aarch64"
git-tree-sha1 = "479d19e03f894e9a6c2a2611d2298e9c9e8dc687"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "4053c02649595d34121a38fb204fe2528a083108e24a00e74a03b87a6b5d0090"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "b13f7701b69f8ca4fce69fcd3e702663169324ae"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "e6123ff46526b68fec5bb97bc78fc8ef752edcb32e85f1c904d8c23c639157f3"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "b2a13388f9b1790a133da6682d3388110574ba36"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "97b57726a431e36f653259eb8c35447b50f7191269004676197b1cb942397073"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
