[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "b91fa9947ccc68de25fefbe585ef8b38d88a4c58"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "7d33525d4f0280506052b063b12eb884da3811271c674eb77268f36565cd5e92"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "94ee41447276194d06ffe96a8ffacde05a185a10"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "1ccce8fa0093892f85aa8cca2591a00ca963a4652e1c50c7ab6c4347a13164be"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d4ef9f7091546244c32ce98a8c0493fb7c14430c"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "6d86e95f86ff425d983481ba5c9d2f27b4851af5db63cdbe518a57ac3e7cd335"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
