[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "0e8408f7634e0c9c410f2a4867ee4b0ea112d29b"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "3848ff2957158142a08332afc93534890099830b3187a9deadfcb58e8bc3f531"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.16-GCCBoostrap/Ncurses-v1.0.16-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "05baa96b53573b5c59125d493a8fa5fea5f78b78"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "2af6b10b55bea73499d36ba37fcb7a7547c511c51535f28279621b8dc86aae13"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.16-GCCBoostrap/Ncurses-build_log-v1.0.16-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a5d14d621dd536bb01f3069d5f2c70b1ff80397f"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "a13070683845ffd84b74c569f5a76b9612f65a6c198354d1156993af0d9401b9"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.16-GCCBoostrap/Ncurses-extract_log-v1.0.16-x86_64-linux-gnu.tar.gz"
