[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "0632a73765544b8ae2a64f2c2fee6a7216176d53"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "193c17851b4ca5df09772c7e9325f649a750dd520bdb0a5207a3f083804ff353"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBoostrap-aarch64-linux-gnu/Ncurses-v6.4.2-aarch64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "aarch64"
git-tree-sha1 = "0ad65789ec9968f5576ee35e167c1d0a647a8dff"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "a247be14da17e3c3fe6ba2fc5079934f01d2a65529fb2d1fcf23e1baebb28e59"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBoostrap-aarch64-linux-gnu/Ncurses-build_log-v6.4.2-aarch64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "aarch64"
git-tree-sha1 = "7fa74e79f5822d273036d209c0c767d4dab82b72"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "ea9271036dee89fa5cded6843a7eb25ccc8c6c1893875a04b2c5b8059bae711f"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBoostrap-aarch64-linux-gnu/Ncurses-extract_log-v6.4.2-aarch64-linux-gnu.tar.gz"
