[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "4fca2426c9ed10b4a0998d9d8cbd855ff0add91d"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "2fd5c5c15776db43ff7add8649a6cdb3768cd050779b1f258562ef73214a8549"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-v6.4.4-x86_64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "40ccfda7e2462c7e9a2201a660e77046a8cc9737"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "20bd8cda0885c08cff310283c0d5a02600259fcaa320426efa5bee7280de6d23"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-v6.4.4-i686-linux-gnu.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "3c084ed35bd3b539b7eb5fb744d6a77a41549230"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "0d58e639b4bd7f712b90efb918e26298f78dfec360f9de4558329b8a8bc9ca2e"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-v6.4.4-aarch64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "29b453be8cd93911aa9a6585b52a50801c015615"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "4192519e63cfc64651197b268e7370a68421135a7d7a6b124e4c895d4eefb57b"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-v6.4.4-armv7l-linux-gnueabihf.tar.gz"
[[Ncurses]]
arch = "powerpc64le"
git-tree-sha1 = "12c59ecd80c0b75871650647c507aff8fce67781"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "52da5bc970df8f3c4b0b7efd2d93c9486f9181e570b6e7307e1d49d74954e897"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-v6.4.4-powerpc64le-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "c059d1d0102353759f6c28ff4da7b14baca8dd66"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "26289b9631e7ed6ae6967585514aca6ee58b583b800e563ccb18cdce9389f1f7"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-build_log-v6.4.4-x86_64-linux-gnu.tar.gz"
[[Ncurses-build_log]]
arch = "i686"
git-tree-sha1 = "52e3ec8cd5d40144251ff874392efe65a03e7754"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "e66099e1da96cc3be5163021bfefc59071ccdc6f8bb1a712bf6353f1271dde39"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-build_log-v6.4.4-i686-linux-gnu.tar.gz"
[[Ncurses-build_log]]
arch = "aarch64"
git-tree-sha1 = "ebec2c7b0598edc82997f0aa02916ca73e4bfdb4"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "97864a791548d8a985ef2bd218c9b30fb6812e57c0156c8ffef1c94cbe524573"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-build_log-v6.4.4-aarch64-linux-gnu.tar.gz"
[[Ncurses-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "35b75ce3623435673aa0037f97649f3e8f3e9d43"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "deb80c9dfdf69f49fb9dc6d801fa3f2354e58dafb47856b031673c43fae7e6f4"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-build_log-v6.4.4-armv7l-linux-gnueabihf.tar.gz"
[[Ncurses-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "9596406a42e147e9f42675c25f93a4dfbcc14e76"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "8696c78365b3ce9f18f337e626337836375233cfe319a6ad16ef5eacda65a78c"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-build_log-v6.4.4-powerpc64le-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4fb773dc74bcad7685b377735a6073c5fab219f0"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "3ea47f914a4b0bc26d4448b58f11d2434ffdaac787618561729642886cb8aa05"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-extract_log-v6.4.4-x86_64-linux-gnu.tar.gz"
[[Ncurses-extract_log]]
arch = "i686"
git-tree-sha1 = "e4175d4c477b50334d45a7a0a00285a96d8654fe"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "4b4e5e2c406824abd7c6acf9e1407f17b9cb5f0ad0a10782ef4bc2f02a3759d2"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-extract_log-v6.4.4-i686-linux-gnu.tar.gz"
[[Ncurses-extract_log]]
arch = "aarch64"
git-tree-sha1 = "125d1571c9e854a8beb4e4d8a87bb9b31094b4a2"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "a48970a17e41554935c3fec3d9bf72f1f37d146b969fa589c8f83dca5e41ffa1"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-extract_log-v6.4.4-aarch64-linux-gnu.tar.gz"
[[Ncurses-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f5a059aa0cc19e9362a6ed0449298969b38a4ce0"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "68b00ca486e110ad126f4992f15a359e05fbfabc64977cc24903f559fff0cb83"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-extract_log-v6.4.4-armv7l-linux-gnueabihf.tar.gz"
[[Ncurses-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "ac35b135c178a52ec6674ae3dcd8269151b6fd59"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "a3bfaf4a0acc643f1a95c4f17536efc756f518834b570d6a4bc893a61946bdb8"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap/Ncurses-extract_log-v6.4.4-powerpc64le-linux-gnu.tar.gz"
