[[default]]
arch = "aarch64"
git-tree-sha1 = "13bbda9ce4b215da4320ca8a3a021f6f694337c2"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "7a073b77c49ec81e59739a2b9b93d12cd0e9722a447ff0c8137cfbe55a7e1f30"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "f5b69d77e7e02b8ff9b27d57de37ec9d0e149f03"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "7a323992c22ed5db0685ed9fab6432ac4eb8c35fa6fc1f0bb5fc9a6a1e0145bf"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "feb9041ffd3441156d9480ffc6e236503544bf75"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "ef76f24a57c4acf7ad96805d7e68a0ec7165276cdec8b64e22d3365300b60296"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
