[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "a467d9c3e1b9b8e194b5250d156c2197128f2a5f"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "677eeab76129022b6ee743a9ec6e6a02ebdcd8430e2cec3b485ae3c860cafd94"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "9c67a0e69ef6ba06fffc08237812a700df433e71"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "093cfebb4d72ab9a941478661704603d13e28f20e4245b1ef02ab4b18cc66b5a"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "cabcc0b82ccf95d58d7ccecf67795509504c5003"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "871a83c8fe980f2978c4204ed10ed7a0cf83964c59b9031e00b86e6f0842f38b"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
