[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "72a152fed147ce53f4e9f5985ecfd8dda5cf2d47"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "88c155083ea2d5fbaa08d84a634a77bb79eee011f34507c5180c493e53028be3"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "76e2c46512fbfd147063452d9b32cade31a813d5"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "63ce5fef9ab27397899ea60b383f33e2c4ac5de8d65a61e7c4fa94bb9007f51f"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e85c974f25c0e7807072f6a21481ebd84fcf28fe"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "ca2ec68d6e433652a22bb07f216de5da61844b6c10a9f37b7bda551411aebad5"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
