[[default]]
arch = "aarch64"
git-tree-sha1 = "163246fb094541435e51384ff2477aafe06d4d80"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "b731a54e88c51d5fd717bef7928494e4b738f6fe4c203ca1c6c3c10efa5e9481"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "a6149c82ababb9d1f20d29c2d142f499f8fb55e4"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "3586bd175502b109bc156029b9cdb5de889492c4f9eabf4ad9d3ac8c741d5517"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "fe5891da15682dad026c4ffaae5bc8b41f0b3162"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "9b2f7005a94f75d05f22b065f6afcdda49cce5e7642907dfa5aa5e457a62d9ac"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
