[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "4e2fac0db9478ea55ea619740261f288f987916f"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "4ff7488cce79ecf39734f52e123daca6766d89604ac79b5ddac925f9328b45ba"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "4d9d9adf944394dc56c3b2e2d9bbcd21cc0cdb72"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "a4c500a3feea580cd2dcebe6638338b8502fa94b6cd67f23207668e841f43fa5"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "8b731f40a4e0a68b661a6543150dfc2a4248d5d6"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "5bf4a18d06a510b7d0ace1bac31dae8f93da3d4f4b3f38ee6940f5e16060e76b"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
