[[default]]
arch = "aarch64"
git-tree-sha1 = "93ee7396f9b292bd5300212a5dd0d42b576bcf05"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "9574391dbd688b80d961befc7a1258c381399f0483feb8489c41d14239ec4f29"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "3bd5955f4256b9f2346834fc5e2b2f02cc978aa7"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "e7a508c419dcf5b14bd1c7ecf0c5c0ae35b0d3f30073c4125603fed19b67b63c"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "feb9041ffd3441156d9480ffc6e236503544bf75"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "5ae6af77a24255d207bd7a007cf7ee617addc2ed1e96b69f6fc3c4ddad40ddde"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
