[[default]]
arch = "aarch64"
git-tree-sha1 = "ffd06e9987666daea7556290d96dbb095e7d87f0"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "6182b523eb64ff45f6ff0f34effcc911bebcf570b821aebf4c6c8ff35068edc7"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "1eef78c3cdd6eb587e3be8ffd31d49cf17fe348d"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "5e2bc0d78d845300032e069175d3e1aed1533579850baa2a1dbdb15b9164eeb9"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "3db15b448a70a856e8394ed08b1ab8acb4f40c4f"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "5a3224c02208dae8c78a182daae9ba0f3138dfeae2c9fcb0098119e495fbb600"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
