[[default]]
arch = "aarch64"
git-tree-sha1 = "29d59fdd9f8de7f6ae4226733f8566d8b5e49bd6"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "58cdca419f0d138ca42d1f9fa4d7c207c37af8e30485e51d1fc73f85d5ca4098"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "6d113bcae2dc231e4f2766744ce5b3fa86692646"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "cb0ce24c7c4dd58669de423415a7b74b220309d784f3bea394e4ac884c923bbf"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "b2a13388f9b1790a133da6682d3388110574ba36"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "47843dd9b9e9ab365415edc82964061bf938305a5145fdb76670f4f260e0fe8d"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
