[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "e741b9a5f494555dbf7a2504e398d62b4e2a10ca"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "9034614df4bb8858cdf36167a4c8adf17c6457495513fb0fec6660bac4212af5"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBootstrap-x86_64-linux-gnu/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "x86_64"
git-tree-sha1 = "a2ac4a0f5c00b7f0d9fd3a122167ec9650ffd5fc"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "94694f4ec2309fdf27b73822a14cc54de77c4566a991ed68aa8eba9bc132d732"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBootstrap-x86_64-linux-gnu/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "x86_64"
git-tree-sha1 = "bfaba34ccdedf000c86a0170175060e9bc591520"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "3b08d9396955c342d1a3e96928d452a3f56fea429bb4b9add41057a4c622bbd4"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2-GCCBootstrap-x86_64-linux-gnu/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"
