[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "baa68ef9a67b35dc73d5aba4bda83d7f0b9767ef"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "dcd08ee61ec21d85271dc9e86e8f2b85531c450f9c75ab1bc072bb2fdcb6ffca"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0-bb2_tests/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[Ncurses-build_log]]
arch = "aarch64"
git-tree-sha1 = "67b8ce7509d1e8d0cfe29f6aa5f3eb9d1dc35521"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-build_log.download]]
    sha256 = "0a3a19b05bd42684af2b98bab18de983127e3439fb7e195666b59e0a09e10f34"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0-bb2_tests/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[Ncurses-extract_log]]
arch = "aarch64"
git-tree-sha1 = "feb9041ffd3441156d9480ffc6e236503544bf75"
lazy = true
libc = "glibc"
os = "linux"

    [[Ncurses-extract_log.download]]
    sha256 = "5b335517235aee4d2d8ccab1a684350f5edd7f31bc01c24e1f3c577d1b1a2d95"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0-bb2_tests/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
