[[default]]
arch = "aarch64"
git-tree-sha1 = "2408e559d450a63fd63169175865025f70ad5c3e"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "a18f1c34f664399f8790d0ac9fe267f43afcfd2eb1a501738fa6e3caaa86583f"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "8a3a55127edc25dd621dd093b74f5975aa75f431"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "b51882dd2830ed9a824aec22bb647fff9c07fce8dd407d04a9cee5b7856d2b8d"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "b2a13388f9b1790a133da6682d3388110574ba36"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "aeb260a46a033c6280246d1d57481f6ae3332e6416d39ac066429e428a3206ac"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
