[[default]]
arch = "aarch64"
git-tree-sha1 = "915a038581a26c3663bc6cb6c32a687680ce7f88"
libc = "glibc"
os = "linux"

    [[default.download]]
    sha256 = "be9b63e97dae1ad4c614b1e4c9d262a17f25cda3f3e0603bf4ea16bca0a2dbd8"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-build_log]]
arch = "aarch64"
git-tree-sha1 = "dab79672133aa71c7d6d4b27dffe1206cc9b59c2"
lazy = true
libc = "glibc"
os = "linux"

    [[default-build_log.download]]
    sha256 = "fdd4c4fac8bb97b7077af3587196e5424acf095742f39ac60d8a3fa47778508f"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

[[default-extract_log]]
arch = "aarch64"
git-tree-sha1 = "b2a13388f9b1790a133da6682d3388110574ba36"
lazy = true
libc = "glibc"
os = "linux"

    [[default-extract_log.download]]
    sha256 = "86b6db39ec328d3bf080133f4a2ec1d68f5c04279442ea167ecf44d6ef0095ed"
    url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"
