name = "Ncurses"
version = "6.4.3"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Ncurses"
lazy = "false"
src_version = "6.4.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:de1b94dcff5d606f64c34b6dcd06db6f5f5b27e3"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:22a45b4afdb6ef108e897a283d8a204a640cbd54d8eb5d1e900a1c3f5750969c"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.3-GCCBootstrap-x86_64-linux-gnu/Ncurses-build_log-v6.4.3-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:0ecdc2a77fa0b2efc40ce7aecae17d761e647a59"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:28078c959dca68af34c5002d9038fdd6787fee75f3fed59d28c376ebef932863"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.3-GCCBootstrap-x86_64-linux-gnu/Ncurses-extract_log-v6.4.3-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:79fab2cacfe4302c37ba8404d8567eb760db0eb4"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:8af121a1a1bf1d768fa79fe4b4ad3e854e535eb687c5fefb7eddcbffe96c19c8"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.3-GCCBootstrap-x86_64-linux-gnu/Ncurses-v6.4.3-x86_64-linux-gnu.tar.gz"
