name = "Ncurses"
version = "1.0.0"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "default"
lazy = "false"
src_version = "6.4.0"
platform = "aarch64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:1eef78c3cdd6eb587e3be8ffd31d49cf17fe348d"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:5e2bc0d78d845300032e069175d3e1aed1533579850baa2a1dbdb15b9164eeb9"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:3db15b448a70a856e8394ed08b1ab8acb4f40c4f"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:5a3224c02208dae8c78a182daae9ba0f3138dfeae2c9fcb0098119e495fbb600"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:ffd06e9987666daea7556290d96dbb095e7d87f0"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:6182b523eb64ff45f6ff0f34effcc911bebcf570b821aebf4c6c8ff35068edc7"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"
