name = "Ncurses"
version = "1.0.1"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Ncurses"
lazy = "false"
src_version = "6.4.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:34410b4a588f9890a4b80c627c88aa18f0d65a65"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:5c113baf0296061512c63abb9dbc7069118c050421ff1e0c8a777da3dfc77366"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.1-GCCBoostrap-x86_64-linux-gnu/Ncurses-build_log-v1.0.1-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:1944ccc11161b7c9de092acd5e685e72822f5034"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:f93ab48f398235de68f83185a7e8d5b1aab99053ef1f2a3ecd722c0c9ad9f0df"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.1-GCCBoostrap-x86_64-linux-gnu/Ncurses-extract_log-v1.0.1-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:797d1169e1db03a079d25066bd20fb9928bb4cf2"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:7fa7a714a429fe78adfccaabd40fbd7757afa22e330c6b274e4934cd70be7c3c"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.1-GCCBoostrap-x86_64-linux-gnu/Ncurses-v1.0.1-x86_64-linux-gnu.tar.gz"
