name = "Ncurses"
version = "1.0.0"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Ncurses"
lazy = "false"
src_version = "6.4.0"
platform = "aarch64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:67b8ce7509d1e8d0cfe29f6aa5f3eb9d1dc35521"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:0a3a19b05bd42684af2b98bab18de983127e3439fb7e195666b59e0a09e10f34"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0-bb2_tests/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:feb9041ffd3441156d9480ffc6e236503544bf75"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:5b335517235aee4d2d8ccab1a684350f5edd7f31bc01c24e1f3c577d1b1a2d95"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0-bb2_tests/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:baa68ef9a67b35dc73d5aba4bda83d7f0b9767ef"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:dcd08ee61ec21d85271dc9e86e8f2b85531c450f9c75ab1bc072bb2fdcb6ffca"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0-bb2_tests/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"
