name = "Ncurses"
version = "1.0.16"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Ncurses"
lazy = "false"
src_version = "6.4.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:05baa96b53573b5c59125d493a8fa5fea5f78b78"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:2af6b10b55bea73499d36ba37fcb7a7547c511c51535f28279621b8dc86aae13"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.16-GCCBoostrap/Ncurses-build_log-v1.0.16-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:a5d14d621dd536bb01f3069d5f2c70b1ff80397f"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:a13070683845ffd84b74c569f5a76b9612f65a6c198354d1156993af0d9401b9"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.16-GCCBoostrap/Ncurses-extract_log-v1.0.16-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:0e8408f7634e0c9c410f2a4867ee4b0ea112d29b"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:3848ff2957158142a08332afc93534890099830b3187a9deadfcb58e8bc3f531"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.16-GCCBoostrap/Ncurses-v1.0.16-x86_64-linux-gnu.tar.gz"
