name = "Ncurses"
version = "1.0.14"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Ncurses"
lazy = "false"
src_version = "6.4.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:bfb56decfdbfe9cbf252c90b848ae018087321c0"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:eacced7047b784e8ee2a6085d1fd3329f5351068dcf83095c7a3201a952ec67a"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.14-GCCBoostrap/Ncurses-build_log-v1.0.14-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:93ff4924259fde88dba9d4ce6d5eb68a2054103b"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:5d4f8dcb43be630667f612f3aeef65da8a40c115a716c3abd692ea37b18f0816"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.14-GCCBoostrap/Ncurses-extract_log-v1.0.14-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:0e4c0f13222d2bdc6942ae38831d36f598ec9868"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:6b0333c1aa072515b13cb35a2f047494e76e6002918f66484f952401b97d1593"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.14-GCCBoostrap/Ncurses-v1.0.14-x86_64-linux-gnu.tar.gz"
