name = "Ncurses"
version = "6.4.4"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Ncurses"
lazy = "false"
src_version = "6.4.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:5eab829804ab3dfc56f228b3188e2aa505a21644"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:0083d29a0e01de14f5a3a7eaa393e375bd4ff2d398c90945a7d049173c09218b"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap-x86_64-linux-gnu/Ncurses-build_log-v6.4.4-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:757564895024bed42d9d935b3a2e20f75b48d2c8"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:4fcb1c4c3baa9464d72dd3204708d3058d328d0fdaa4ec5a8c13ce14862c43f7"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap-x86_64-linux-gnu/Ncurses-extract_log-v6.4.4-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:ba7d02890d2a36339e6736d808a4767634c97a30"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:ba3b5ba99d6cdccf8425f37c9bffb54da28d08487a9fa4f1acc4cc81de70b7ba"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.4-GCCBootstrap-x86_64-linux-gnu/Ncurses-v6.4.4-x86_64-linux-gnu.tar.gz"
