name = "Ncurses"
version = "6.4.2"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Ncurses"
lazy = "false"
src_version = "6.4.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:9c67a0e69ef6ba06fffc08237812a700df433e71"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:093cfebb4d72ab9a941478661704603d13e28f20e4245b1ef02ab4b18cc66b5a"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-build_log-v6.4.2-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:cabcc0b82ccf95d58d7ccecf67795509504c5003"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:871a83c8fe980f2978c4204ed10ed7a0cf83964c59b9031e00b86e6f0842f38b"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-extract_log-v6.4.2-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:a467d9c3e1b9b8e194b5250d156c2197128f2a5f"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:677eeab76129022b6ee743a9ec6e6a02ebdcd8430e2cec3b485ae3c860cafd94"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v6.4.2/Ncurses-v6.4.2-x86_64-linux-gnu.tar.gz"
