name = "Ncurses"
version = "1.0.0"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "default"
lazy = "false"
src_version = "6.4.0"
platform = "aarch64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:3bd5955f4256b9f2346834fc5e2b2f02cc978aa7"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:e7a508c419dcf5b14bd1c7ecf0c5c0ae35b0d3f30073c4125603fed19b67b63c"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-build_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:feb9041ffd3441156d9480ffc6e236503544bf75"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:5ae6af77a24255d207bd7a007cf7ee617addc2ed1e96b69f6fc3c4ddad40ddde"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-extract_log-v1.0.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:93ee7396f9b292bd5300212a5dd0d42b576bcf05"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:9574391dbd688b80d961befc7a1258c381399f0483feb8489c41d14239ec4f29"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.0/Ncurses-v1.0.0-aarch64-linux-gnu.tar.gz"
