name = "Ncurses"
version = "1.0.10"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Ncurses"
lazy = "false"
src_version = "6.4.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:55534fe1751ab59eca809b22c946867c7f4e65ef"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:d805ca2d84f4db5afd5ef703b8e25641123b4d2d7d3557cf11ef35410f355ae1"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.10-GCCBoostrap/Ncurses-build_log-v1.0.10-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:0b61ded3a2d3d51364e11998119404e4d84dc8c3"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:333e2722fa420cc36b004c6a96ea3c97e20d483652178557d1b117b242d082b7"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.10-GCCBoostrap/Ncurses-extract_log-v1.0.10-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:0a59dc7e6a1255266572f3d6479449a89883cfe5"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:b42471a6db7cb8be5847bc605469acc1007ff9cb23c5badb2ceca46e2ab4ce6d"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.10-GCCBoostrap/Ncurses-v1.0.10-x86_64-linux-gnu.tar.gz"
