name = "Ncurses"
version = "1.0.11"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Ncurses"
lazy = "false"
src_version = "6.4.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:de190738cf4fbae9db410533cd14221c4340ee82"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:aa0fa78af02bf83509767cad59618350770f82e686b7c56d42e1c15ca2fcbe3a"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.11-GCCBoostrap/Ncurses-build_log-v1.0.11-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:e06bb4b577f6618a66c8d580d31e905b2d6bd42c"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:ba54d27a9bccb67e240570165e4bdd8ccfd9d2c4ad7453b1689a5f361fbfcbdd"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.11-GCCBoostrap/Ncurses-extract_log-v1.0.11-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = ["libncurses"]
    name = "libform"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libformw.so.6"
    type = "library"
    path = "lib/libformw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libpanel"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpanelw.so.6"
    type = "library"
    path = "lib/libpanelw.so.6.4"
    [[builds.products]]
    deps = []
    name = "libncurses"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libncursesw.so.6"
    type = "library"
    path = "lib/libncursesw.so.6.4"
    [[builds.products]]
    deps = ["libncurses"]
    name = "libmenu"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libmenuw.so.6"
    type = "library"
    path = "lib/libmenuw.so.6.4"

    [[builds.sources]]
    treehash = "sha1:dcdda1cd733512a0f52c7b01f16e344e2bb41e2a"
    url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz"

    [builds.artifact]
    treehash = "sha1:26c554147c849b1e9dd589cfbceeffac4ad940ef"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:52156d6076169fff9c78d4c2954c3dff7cecbd7bc237827a0bee11e04815d4a1"
        url = "https://github.com/staticfloat/Ncurses_jll.jl/releases/download/v1.0.11-GCCBoostrap/Ncurses-v1.0.11-x86_64-linux-gnu.tar.gz"
